#!/bin/sh

ulimit -t 60

set -e
/usr/bin/pulledpork.pl -P -c /etc/pulledpork/pulledpork.conf
cd /etc/snort/rules
set +e
/usr/bin/snort2lua -c snort.rules -r snort3.rules
kill -SIGHUP "$(cat /var/log/snort/snort.pid)"
